import { Metadata } from "next";

export const metadata:Metadata = {
  title:{
    absolute:"",
    default:"Next.js Tutorial - CodeEvolution",
    template:"%s | CodeEvolution "
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-red-500 p-4">
        <p>Header</p>
        </header>
        
        {children}
        <footer className="bg-red-500 p-4">
          <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}
